// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module expand_mat_expand_mat_Pipeline_VITIS_LOOP_41_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        outbuf_address0,
        outbuf_ce0,
        outbuf_q0,
        outbuf_address1,
        outbuf_ce1,
        outbuf_q1,
        tmp_2,
        mat_address0,
        mat_ce0,
        mat_we0,
        mat_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] outbuf_address0;
output   outbuf_ce0;
input  [7:0] outbuf_q0;
output  [9:0] outbuf_address1;
output   outbuf_ce1;
input  [7:0] outbuf_q1;
input  [12:0] tmp_2;
output  [12:0] mat_address0;
output   mat_ce0;
output   mat_we0;
output  [31:0] mat_d0;

reg ap_idle;
reg[9:0] outbuf_address0;
reg outbuf_ce0;
reg outbuf_ce1;
reg mat_ce0;
reg mat_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln41_fu_131_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] ctr_1_reg_248;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln41_reg_254;
wire   [9:0] empty_fu_140_p1;
reg   [9:0] empty_reg_258;
reg   [7:0] outbuf_load_reg_273;
wire    ap_block_pp0_stage2_11001;
reg   [7:0] outbuf_load_1_reg_278;
wire   [22:0] val_fu_185_p4;
reg   [22:0] val_reg_288;
wire   [0:0] icmp_ln48_fu_193_p2;
reg   [0:0] icmp_ln48_reg_293;
wire   [12:0] add_ln49_fu_211_p2;
reg   [12:0] add_ln49_reg_297;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln42_fu_150_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln43_fu_155_p1;
wire   [63:0] zext_ln44_fu_176_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln49_1_fu_225_p1;
reg   [31:0] pos_fu_48;
wire   [31:0] pos_3_fu_160_p2;
wire    ap_loop_init;
reg   [31:0] ctr_fu_52;
wire   [31:0] ctr_2_fu_199_p2;
wire    ap_block_pp0_stage0;
wire   [23:0] tmp_fu_121_p4;
wire   [9:0] pos_1_fu_144_p2;
wire   [9:0] pos_2_fu_171_p2;
wire   [6:0] trunc_ln45_fu_181_p1;
wire   [7:0] trunc_ln49_fu_204_p1;
wire   [12:0] zext_ln49_fu_207_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_284;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

expand_mat_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ctr_fu_52 <= 32'd0;
        end else if ((1'b1 == ap_condition_284)) begin
            ctr_fu_52 <= ctr_2_fu_199_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        pos_fu_48 <= 32'd0;
    end else if (((icmp_ln41_fu_131_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        pos_fu_48 <= pos_3_fu_160_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_254 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln48_fu_193_p2 == 1'd1))) begin
        add_ln49_reg_297 <= add_ln49_fu_211_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ctr_1_reg_248 <= ctr_fu_52;
        icmp_ln41_reg_254 <= icmp_ln41_fu_131_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_131_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        empty_reg_258 <= empty_fu_140_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_254 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln48_reg_293 <= icmp_ln48_fu_193_p2;
        val_reg_288 <= val_fu_185_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_254 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        outbuf_load_1_reg_278 <= outbuf_q0;
        outbuf_load_reg_273 <= outbuf_q1;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_131_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mat_ce0 = 1'b1;
    end else begin
        mat_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln48_reg_293 == 1'd1))) begin
        mat_we0 = 1'b1;
    end else begin
        mat_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            outbuf_address0 = zext_ln44_fu_176_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            outbuf_address0 = zext_ln43_fu_155_p1;
        end else begin
            outbuf_address0 = 'bx;
        end
    end else begin
        outbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        outbuf_ce0 = 1'b1;
    end else begin
        outbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        outbuf_ce1 = 1'b1;
    end else begin
        outbuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_fu_211_p2 = (tmp_2 + zext_ln49_fu_207_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_284 = ((icmp_ln41_reg_254 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln48_fu_193_p2 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ctr_2_fu_199_p2 = (ctr_1_reg_248 + 32'd1);

assign empty_fu_140_p1 = pos_fu_48[9:0];

assign icmp_ln41_fu_131_p2 = ((tmp_fu_121_p4 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_193_p2 = ((val_fu_185_p4 < 23'd8380417) ? 1'b1 : 1'b0);

assign mat_address0 = zext_ln49_1_fu_225_p1;

assign mat_d0 = val_reg_288;

assign outbuf_address1 = zext_ln42_fu_150_p1;

assign pos_1_fu_144_p2 = (empty_fu_140_p1 + 10'd1);

assign pos_2_fu_171_p2 = (empty_reg_258 + 10'd2);

assign pos_3_fu_160_p2 = (pos_fu_48 + 32'd3);

assign tmp_fu_121_p4 = {{ctr_fu_52[31:8]}};

assign trunc_ln45_fu_181_p1 = outbuf_q0[6:0];

assign trunc_ln49_fu_204_p1 = ctr_1_reg_248[7:0];

assign val_fu_185_p4 = {{{trunc_ln45_fu_181_p1}, {outbuf_load_1_reg_278}}, {outbuf_load_reg_273}};

assign zext_ln42_fu_150_p1 = pos_fu_48;

assign zext_ln43_fu_155_p1 = pos_1_fu_144_p2;

assign zext_ln44_fu_176_p1 = pos_2_fu_171_p2;

assign zext_ln49_1_fu_225_p1 = add_ln49_reg_297;

assign zext_ln49_fu_207_p1 = trunc_ln49_fu_204_p1;

endmodule //expand_mat_expand_mat_Pipeline_VITIS_LOOP_41_4
