// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="expand_mat_expand_mat,hls_ip_2022_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.272375,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=14,HLS_SYN_DSP=0,HLS_SYN_FF=3696,HLS_SYN_LUT=18472,HLS_VERSION=2022_1}" *)

module expand_mat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_address0,
        mat_ce0,
        mat_we0,
        mat_d0,
        rho_address0,
        rho_ce0,
        rho_q0
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] mat_address0;
output   mat_ce0;
output   mat_we0;
output  [31:0] mat_d0;
output  [4:0] rho_address0;
output   rho_ce0;
input  [7:0] rho_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [4:0] add_ln34_1_fu_262_p2;
reg   [4:0] add_ln34_1_reg_433;
wire    ap_CS_fsm_state3;
wire   [2:0] select_ln34_fu_286_p3;
reg   [2:0] select_ln34_reg_438;
wire    ap_CS_fsm_state4;
wire   [2:0] select_ln34_1_fu_294_p3;
reg   [2:0] select_ln34_1_reg_444;
wire   [12:0] tmp_2_fu_349_p3;
reg   [12:0] tmp_2_reg_451;
wire    ap_CS_fsm_state10;
wire   [9:0] add_ln419_fu_363_p2;
reg   [9:0] add_ln419_reg_459;
wire    ap_CS_fsm_state11;
wire   [0:0] icmp_ln414_fu_357_p2;
wire   [2:0] add_ln420_fu_369_p2;
reg   [2:0] add_ln420_reg_464;
reg   [7:0] t_address0;
reg    t_ce0;
reg    t_we0;
reg   [7:0] t_d0;
wire   [7:0] t_q0;
reg   [7:0] t_address1;
reg    t_ce1;
wire   [7:0] t_q1;
reg    t_ce2;
wire   [7:0] t_q2;
reg    t_ce3;
wire   [7:0] t_q3;
reg    t_ce4;
wire   [7:0] t_q4;
reg    t_ce5;
wire   [7:0] t_q5;
reg    t_ce6;
wire   [7:0] t_q6;
reg    t_ce7;
wire   [7:0] t_q7;
reg   [4:0] s_address0;
reg    s_ce0;
reg    s_we0;
reg   [63:0] s_d0;
wire   [63:0] s_q0;
reg   [4:0] s_address1;
reg    s_ce1;
reg    s_we1;
wire   [63:0] s_q1;
reg   [5:0] inbuf_address0;
reg    inbuf_ce0;
reg    inbuf_we0;
reg   [7:0] inbuf_d0;
wire   [7:0] inbuf_q0;
reg   [9:0] outbuf_address0;
reg    outbuf_ce0;
reg    outbuf_we0;
wire   [7:0] outbuf_q0;
reg   [9:0] outbuf_address1;
reg    outbuf_ce1;
reg    outbuf_we1;
wire   [7:0] outbuf_q1;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_done;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_idle;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_ready;
wire   [4:0] grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_rho_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_rho_ce0;
wire   [5:0] grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_ce0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_we0;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_d0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_done;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_idle;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_ready;
wire   [4:0] grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_ce0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_we0;
wire   [63:0] grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_d0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_done;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_idle;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_ready;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_ce0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_we0;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_d0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_done;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_idle;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_ready;
wire   [5:0] grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_inbuf_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_inbuf_ce0;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_ce0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_we0;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_d0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_done;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_idle;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_ready;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce0;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address1;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce1;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address2;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce2;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address3;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce3;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address4;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce4;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address5;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce5;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address6;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce6;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address7;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce7;
wire   [4:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_ce0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_we0;
wire   [63:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_d0;
wire   [4:0] grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_address1;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_ce1;
wire    grp_KeccakF1600_StatePermute_fu_215_ap_start;
wire    grp_KeccakF1600_StatePermute_fu_215_ap_done;
wire    grp_KeccakF1600_StatePermute_fu_215_ap_idle;
wire    grp_KeccakF1600_StatePermute_fu_215_ap_ready;
wire   [4:0] grp_KeccakF1600_StatePermute_fu_215_state_address0;
wire    grp_KeccakF1600_StatePermute_fu_215_state_ce0;
wire    grp_KeccakF1600_StatePermute_fu_215_state_we0;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_215_state_d0;
wire   [4:0] grp_KeccakF1600_StatePermute_fu_215_state_address1;
wire    grp_KeccakF1600_StatePermute_fu_215_state_ce1;
wire    grp_KeccakF1600_StatePermute_fu_215_state_we1;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_215_state_d1;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_done;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_idle;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_ready;
wire   [9:0] grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_ce0;
wire   [9:0] grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_address1;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_ce1;
wire   [12:0] grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_ce0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_we0;
wire   [31:0] grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_d0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_done;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_idle;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_ready;
wire   [4:0] grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_s_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_s_ce0;
wire   [9:0] grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_address0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_ce0;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_we0;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_d0;
wire   [9:0] grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_address1;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_ce1;
wire    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_we1;
wire   [7:0] grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_d1;
reg   [2:0] nblocks_assign_reg_162;
wire    ap_CS_fsm_state14;
reg   [9:0] idx_reg_173;
reg    grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start_reg;
reg    grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start_reg;
wire   [0:0] icmp_ln34_fu_256_p2;
reg    grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start_reg;
reg    grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_KeccakF1600_StatePermute_fu_215_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start_reg;
wire    ap_CS_fsm_state13;
reg   [2:0] j_fu_98;
wire   [2:0] j_1_fu_375_p2;
reg   [2:0] i_1_fu_102;
reg   [4:0] indvar_flatten_fu_106;
reg    ap_block_state4_on_subcall_done;
wire   [7:0] zext_ln37_fu_312_p1;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [7:0] or_ln389_fu_317_p2;
wire   [0:0] icmp_ln35_fu_280_p2;
wire   [2:0] add_ln34_fu_274_p2;
wire   [6:0] add_ln_fu_302_p4;
wire   [4:0] tmp_fu_327_p3;
wire   [4:0] zext_ln49_fu_324_p1;
wire   [4:0] add_ln49_fu_334_p2;
wire   [4:0] zext_ln49_2_fu_340_p1;
wire   [4:0] add_ln49_1_fu_343_p2;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start_reg = 1'b0;
#0 grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start_reg = 1'b0;
#0 grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start_reg = 1'b0;
#0 grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start_reg = 1'b0;
#0 grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start_reg = 1'b0;
#0 grp_KeccakF1600_StatePermute_fu_215_ap_start_reg = 1'b0;
#0 grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start_reg = 1'b0;
#0 grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start_reg = 1'b0;
end

expand_mat_t_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 200 ),
    .AddressWidth( 8 ))
t_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(t_address0),
    .ce0(t_ce0),
    .we0(t_we0),
    .d0(t_d0),
    .q0(t_q0),
    .address1(t_address1),
    .ce1(t_ce1),
    .q1(t_q1),
    .address2(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address2),
    .ce2(t_ce2),
    .q2(t_q2),
    .address3(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address3),
    .ce3(t_ce3),
    .q3(t_q3),
    .address4(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address4),
    .ce4(t_ce4),
    .q4(t_q4),
    .address5(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address5),
    .ce5(t_ce5),
    .q5(t_q5),
    .address6(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address6),
    .ce6(t_ce6),
    .q6(t_q6),
    .address7(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address7),
    .ce7(t_ce7),
    .q7(t_q7)
);

expand_mat_s_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(s_address0),
    .ce0(s_ce0),
    .we0(s_we0),
    .d0(s_d0),
    .q0(s_q0),
    .address1(s_address1),
    .ce1(s_ce1),
    .we1(s_we1),
    .d1(grp_KeccakF1600_StatePermute_fu_215_state_d1),
    .q1(s_q1)
);

expand_mat_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 33 ),
    .AddressWidth( 6 ))
inbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inbuf_address0),
    .ce0(inbuf_ce0),
    .we0(inbuf_we0),
    .d0(inbuf_d0),
    .q0(inbuf_q0)
);

expand_mat_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 840 ),
    .AddressWidth( 10 ))
outbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outbuf_address0),
    .ce0(outbuf_ce0),
    .we0(outbuf_we0),
    .d0(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_d0),
    .q0(outbuf_q0),
    .address1(outbuf_address1),
    .ce1(outbuf_ce1),
    .we1(outbuf_we1),
    .d1(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_d1),
    .q1(outbuf_q1)
);

expand_mat_expand_mat_Pipeline_VITIS_LOOP_31_1 grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start),
    .ap_done(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_done),
    .ap_idle(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_idle),
    .ap_ready(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_ready),
    .rho_address0(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_rho_address0),
    .rho_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_rho_ce0),
    .rho_q0(rho_q0),
    .inbuf_address0(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_address0),
    .inbuf_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_ce0),
    .inbuf_we0(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_we0),
    .inbuf_d0(grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_d0)
);

expand_mat_expand_mat_Pipeline_VITIS_LOOP_372_1 grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start),
    .ap_done(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_done),
    .ap_idle(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_idle),
    .ap_ready(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_ready),
    .s_address0(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_address0),
    .s_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_ce0),
    .s_we0(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_we0),
    .s_d0(grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_d0)
);

expand_mat_expand_mat_Pipeline_VITIS_LOOP_384_4 grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start),
    .ap_done(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_done),
    .ap_idle(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_idle),
    .ap_ready(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_ready),
    .t_address0(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_address0),
    .t_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_ce0),
    .t_we0(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_we0),
    .t_d0(grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_d0)
);

expand_mat_expand_mat_Pipeline_VITIS_LOOP_386_5 grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start),
    .ap_done(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_done),
    .ap_idle(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_idle),
    .ap_ready(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_ready),
    .inbuf_address0(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_inbuf_address0),
    .inbuf_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_inbuf_ce0),
    .inbuf_q0(inbuf_q0),
    .t_address0(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_address0),
    .t_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_ce0),
    .t_we0(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_we0),
    .t_d0(grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_d0)
);

expand_mat_expand_mat_Pipeline_VITIS_LOOP_390_6 grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start),
    .ap_done(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_done),
    .ap_idle(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_idle),
    .ap_ready(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_ready),
    .t_address0(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address0),
    .t_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce0),
    .t_q0(t_q0),
    .t_address1(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address1),
    .t_ce1(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce1),
    .t_q1(t_q1),
    .t_address2(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address2),
    .t_ce2(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce2),
    .t_q2(t_q2),
    .t_address3(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address3),
    .t_ce3(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce3),
    .t_q3(t_q3),
    .t_address4(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address4),
    .t_ce4(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce4),
    .t_q4(t_q4),
    .t_address5(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address5),
    .t_ce5(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce5),
    .t_q5(t_q5),
    .t_address6(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address6),
    .t_ce6(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce6),
    .t_q6(t_q6),
    .t_address7(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address7),
    .t_ce7(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce7),
    .t_q7(t_q7),
    .s_address0(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_address0),
    .s_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_ce0),
    .s_we0(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_we0),
    .s_d0(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_d0),
    .s_address1(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_address1),
    .s_ce1(grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_ce1),
    .s_q1(s_q1)
);

expand_mat_KeccakF1600_StatePermute grp_KeccakF1600_StatePermute_fu_215(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_KeccakF1600_StatePermute_fu_215_ap_start),
    .ap_done(grp_KeccakF1600_StatePermute_fu_215_ap_done),
    .ap_idle(grp_KeccakF1600_StatePermute_fu_215_ap_idle),
    .ap_ready(grp_KeccakF1600_StatePermute_fu_215_ap_ready),
    .state_address0(grp_KeccakF1600_StatePermute_fu_215_state_address0),
    .state_ce0(grp_KeccakF1600_StatePermute_fu_215_state_ce0),
    .state_we0(grp_KeccakF1600_StatePermute_fu_215_state_we0),
    .state_d0(grp_KeccakF1600_StatePermute_fu_215_state_d0),
    .state_q0(s_q0),
    .state_address1(grp_KeccakF1600_StatePermute_fu_215_state_address1),
    .state_ce1(grp_KeccakF1600_StatePermute_fu_215_state_ce1),
    .state_we1(grp_KeccakF1600_StatePermute_fu_215_state_we1),
    .state_d1(grp_KeccakF1600_StatePermute_fu_215_state_d1),
    .state_q1(s_q1)
);

expand_mat_expand_mat_Pipeline_VITIS_LOOP_41_4 grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start),
    .ap_done(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_done),
    .ap_idle(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_idle),
    .ap_ready(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_ready),
    .outbuf_address0(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_address0),
    .outbuf_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_ce0),
    .outbuf_q0(outbuf_q0),
    .outbuf_address1(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_address1),
    .outbuf_ce1(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_ce1),
    .outbuf_q1(outbuf_q1),
    .tmp_2(tmp_2_reg_451),
    .mat_address0(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_address0),
    .mat_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_ce0),
    .mat_we0(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_we0),
    .mat_d0(grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_d0)
);

expand_mat_expand_mat_Pipeline_VITIS_LOOP_416_2 grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start),
    .ap_done(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_done),
    .ap_idle(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_idle),
    .ap_ready(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_ready),
    .s_address0(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_s_address0),
    .s_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_s_ce0),
    .s_q0(s_q0),
    .idx(idx_reg_173),
    .outbuf_address0(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_address0),
    .outbuf_ce0(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_ce0),
    .outbuf_we0(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_we0),
    .outbuf_d0(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_d0),
    .outbuf_address1(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_address1),
    .outbuf_ce1(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_ce1),
    .outbuf_we1(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_we1),
    .outbuf_d1(grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_KeccakF1600_StatePermute_fu_215_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln414_fu_357_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_KeccakF1600_StatePermute_fu_215_ap_start_reg <= 1'b1;
        end else if ((grp_KeccakF1600_StatePermute_fu_215_ap_ready == 1'b1)) begin
            grp_KeccakF1600_StatePermute_fu_215_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start_reg <= 1'b1;
        end else if ((grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_ready == 1'b1)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln34_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_ready == 1'b1)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln34_fu_256_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start_reg <= 1'b1;
        end else if ((grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_ready == 1'b1)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start_reg <= 1'b1;
        end else if ((grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_ready == 1'b1)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start_reg <= 1'b1;
        end else if ((grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_ready == 1'b1)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start_reg <= 1'b1;
        end else if ((grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_ready == 1'b1)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln414_fu_357_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start_reg <= 1'b1;
        end else if ((grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_ready == 1'b1)) begin
            grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_1_fu_102 <= 3'd0;
    end else if (((icmp_ln414_fu_357_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        i_1_fu_102 <= select_ln34_1_reg_444;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        idx_reg_173 <= 10'd0;
    end else if (((grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        idx_reg_173 <= add_ln419_reg_459;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_106 <= 5'd0;
    end else if (((icmp_ln414_fu_357_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        indvar_flatten_fu_106 <= add_ln34_1_reg_433;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_98 <= 3'd0;
    end else if (((icmp_ln414_fu_357_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        j_fu_98 <= j_1_fu_375_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        nblocks_assign_reg_162 <= 3'd5;
    end else if (((grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        nblocks_assign_reg_162 <= add_ln420_reg_464;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln34_1_reg_433 <= add_ln34_1_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln414_fu_357_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        add_ln419_reg_459 <= add_ln419_fu_363_p2;
        add_ln420_reg_464 <= add_ln420_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        select_ln34_1_reg_444 <= select_ln34_1_fu_294_p3;
        select_ln34_reg_438 <= select_ln34_fu_286_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_2_reg_451[12 : 8] <= tmp_2_fu_349_p3[12 : 8];
    end
end

always @ (*) begin
    if ((grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_KeccakF1600_StatePermute_fu_215_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln34_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln34_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        inbuf_address0 = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        inbuf_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_inbuf_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        inbuf_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_address0;
    end else begin
        inbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        inbuf_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        inbuf_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_inbuf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        inbuf_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_ce0;
    end else begin
        inbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        inbuf_d0 = zext_ln37_fu_312_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        inbuf_d0 = grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_d0;
    end else begin
        inbuf_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        inbuf_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        inbuf_we0 = grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_inbuf_we0;
    end else begin
        inbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outbuf_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outbuf_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_address0;
    end else begin
        outbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outbuf_address1 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_address1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outbuf_address1 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_address1;
    end else begin
        outbuf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outbuf_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outbuf_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_ce0;
    end else begin
        outbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outbuf_ce1 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        outbuf_ce1 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_outbuf_ce1;
    end else begin
        outbuf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outbuf_we0 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_we0;
    end else begin
        outbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        outbuf_we1 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_outbuf_we1;
    end else begin
        outbuf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        s_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_s_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        s_address0 = grp_KeccakF1600_StatePermute_fu_215_state_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        s_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        s_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_address0;
    end else begin
        s_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_address1 = grp_KeccakF1600_StatePermute_fu_215_state_address1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        s_address1 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_address1;
    end else begin
        s_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        s_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_s_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        s_ce0 = grp_KeccakF1600_StatePermute_fu_215_state_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        s_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        s_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_ce0;
    end else begin
        s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_ce1 = grp_KeccakF1600_StatePermute_fu_215_state_ce1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        s_ce1 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_ce1;
    end else begin
        s_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_d0 = grp_KeccakF1600_StatePermute_fu_215_state_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        s_d0 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        s_d0 = grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_d0;
    end else begin
        s_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_we0 = grp_KeccakF1600_StatePermute_fu_215_state_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        s_we0 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_s_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        s_we0 = grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_s_we0;
    end else begin
        s_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_we1 = grp_KeccakF1600_StatePermute_fu_215_state_we1;
    end else begin
        s_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        t_address0 = 64'd167;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_address0 = 64'd33;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        t_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        t_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_address0;
    end else begin
        t_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t_address1 = 64'd167;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        t_address1 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_address1;
    end else begin
        t_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        t_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        t_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_ce0;
    end else begin
        t_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        t_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce1 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce1;
    end else begin
        t_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce2 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce2;
    end else begin
        t_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce3 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce3;
    end else begin
        t_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce4 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce4;
    end else begin
        t_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce5 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce5;
    end else begin
        t_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce6 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce6;
    end else begin
        t_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_ce7 = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_t_ce7;
    end else begin
        t_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        t_d0 = or_ln389_fu_317_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_d0 = 8'd31;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        t_d0 = grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_d0 = grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_d0;
    end else begin
        t_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        t_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        t_we0 = grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_t_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        t_we0 = grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_t_we0;
    end else begin
        t_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln34_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln414_fu_357_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((grp_KeccakF1600_StatePermute_fu_215_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln34_1_fu_262_p2 = (indvar_flatten_fu_106 + 5'd1);

assign add_ln34_fu_274_p2 = (i_1_fu_102 + 3'd1);

assign add_ln419_fu_363_p2 = (idx_reg_173 + 10'd168);

assign add_ln420_fu_369_p2 = ($signed(nblocks_assign_reg_162) + $signed(3'd7));

assign add_ln49_1_fu_343_p2 = (add_ln49_fu_334_p2 + zext_ln49_2_fu_340_p1);

assign add_ln49_fu_334_p2 = (tmp_fu_327_p3 + zext_ln49_fu_324_p1);

assign add_ln_fu_302_p4 = {{{select_ln34_fu_286_p3}, {1'd0}}, {select_ln34_1_fu_294_p3}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_done == 1'b0) | (grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_done == 1'b0));
end

assign grp_KeccakF1600_StatePermute_fu_215_ap_start = grp_KeccakF1600_StatePermute_fu_215_ap_start_reg;

assign grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start = grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_ap_start_reg;

assign grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start = grp_expand_mat_Pipeline_VITIS_LOOP_372_1_fu_193_ap_start_reg;

assign grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start = grp_expand_mat_Pipeline_VITIS_LOOP_384_4_fu_198_ap_start_reg;

assign grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start = grp_expand_mat_Pipeline_VITIS_LOOP_386_5_fu_203_ap_start_reg;

assign grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start = grp_expand_mat_Pipeline_VITIS_LOOP_390_6_fu_209_ap_start_reg;

assign grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start = grp_expand_mat_Pipeline_VITIS_LOOP_416_2_fu_230_ap_start_reg;

assign grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_ap_start_reg;

assign icmp_ln34_fu_256_p2 = ((indvar_flatten_fu_106 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_280_p2 = ((j_fu_98 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln414_fu_357_p2 = ((nblocks_assign_reg_162 == 3'd0) ? 1'b1 : 1'b0);

assign j_1_fu_375_p2 = (select_ln34_reg_438 + 3'd1);

assign mat_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_address0;

assign mat_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_ce0;

assign mat_d0 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_d0;

assign mat_we0 = grp_expand_mat_Pipeline_VITIS_LOOP_41_4_fu_222_mat_we0;

assign or_ln389_fu_317_p2 = (t_q1 | 8'd128);

assign rho_address0 = grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_rho_address0;

assign rho_ce0 = grp_expand_mat_Pipeline_VITIS_LOOP_31_1_fu_185_rho_ce0;

assign select_ln34_1_fu_294_p3 = ((icmp_ln35_fu_280_p2[0:0] == 1'b1) ? add_ln34_fu_274_p2 : i_1_fu_102);

assign select_ln34_fu_286_p3 = ((icmp_ln35_fu_280_p2[0:0] == 1'b1) ? 3'd0 : j_fu_98);

assign tmp_2_fu_349_p3 = {{add_ln49_1_fu_343_p2}, {8'd0}};

assign tmp_fu_327_p3 = {{select_ln34_1_reg_444}, {2'd0}};

assign zext_ln37_fu_312_p1 = add_ln_fu_302_p4;

assign zext_ln49_2_fu_340_p1 = select_ln34_reg_438;

assign zext_ln49_fu_324_p1 = select_ln34_1_reg_444;

always @ (posedge ap_clk) begin
    tmp_2_reg_451[7:0] <= 8'b00000000;
end

endmodule //expand_mat
